<?php

namespace KladionicaBundle\Repository;

/**
 * KosarkaKvoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KosarkaKvoteRepository extends \Doctrine\ORM\EntityRepository
{
}
