<?php

namespace KladionicaBundle\Repository;

/**
 * KvoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KvoteRepository extends \Doctrine\ORM\EntityRepository
{
}
