<?php

namespace KladionicaBundle\Repository;

/**
 * KvotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KvotaRepository extends \Doctrine\ORM\EntityRepository
{
}
