<?php

namespace ProbaBundle\Repository;

/**
 * ProbajRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProbajRepository extends \Doctrine\ORM\EntityRepository
{
}
